//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportRepositoryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightsHistory
    {
        public int FlightID { get; set; }
        public int StationID { get; set; }
        public System.DateTime EnterTime { get; set; }
        public System.DateTime ExitTime { get; set; }
    }
}
