//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int FlightID { get; set; }
        public string State { get; set; }
        public System.DateTime StartRouteTime { get; set; }
    }
}
