//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportLogicService.RepoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RepoServiceReference.IRepository")]
    public interface IRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepository/GetFutureFlights", ReplyAction="http://tempuri.org/IRepository/GetFutureFlightsResponse")]
        DTOs.FlightDTO[] GetFutureFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepository/GetFutureFlights", ReplyAction="http://tempuri.org/IRepository/GetFutureFlightsResponse")]
        System.Threading.Tasks.Task<DTOs.FlightDTO[]> GetFutureFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepository/AddFlightToScedule", ReplyAction="http://tempuri.org/IRepository/AddFlightToSceduleResponse")]
        bool AddFlightToScedule(DTOs.FlightDTO flight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepository/AddFlightToScedule", ReplyAction="http://tempuri.org/IRepository/AddFlightToSceduleResponse")]
        System.Threading.Tasks.Task<bool> AddFlightToSceduleAsync(DTOs.FlightDTO flight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepositoryChannel : AirportLogicService.RepoServiceReference.IRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepositoryClient : System.ServiceModel.ClientBase<AirportLogicService.RepoServiceReference.IRepository>, AirportLogicService.RepoServiceReference.IRepository {
        
        public RepositoryClient() {
        }
        
        public RepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTOs.FlightDTO[] GetFutureFlights() {
            return base.Channel.GetFutureFlights();
        }
        
        public System.Threading.Tasks.Task<DTOs.FlightDTO[]> GetFutureFlightsAsync() {
            return base.Channel.GetFutureFlightsAsync();
        }
        
        public bool AddFlightToScedule(DTOs.FlightDTO flight) {
            return base.Channel.AddFlightToScedule(flight);
        }
        
        public System.Threading.Tasks.Task<bool> AddFlightToSceduleAsync(DTOs.FlightDTO flight) {
            return base.Channel.AddFlightToSceduleAsync(flight);
        }
    }
}
